### ISSUE TITLE
override Spree::Product#search_data method

### ISSUE THREAD

**Issue by connecticus** [ronzalo/spree_searchkick#1]
Hi Gonzalo, where I must  'override Spree::Product#search_data method'?

Thank you for awesome plugin.

**Comment by ronzalo** [comment]
Decorate your `Spree::Product` on your project (create a file `product_decorator.rb` under `app/models/spree`) and add `search_data` method.
Look this: https://github.com/ronzalo/spree_searchkick/blob/master/app/models/spree/product_decorator.rb#L4
