### ISSUE TITLE
unknown keywords: autocomplete (ArgumentError) error while run bundle exec rails g spree_searchkick:install

### ISSUE THREAD

**Issue by palpandiR** [ronzalo/spree_searchkick#12]
palpandi@railsfactory:~/projects/Spree/mystore$ bundle exec rails g spree_searchkick:install
/home/palpandi/.rvm/gems/ruby-2.2.1/gems/searchkick-2.1.1/lib/searchkick/model.rb:9:in `searchkick': unknown keywords: autocomplete (ArgumentError)
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/app/models/spree/product_decorator.rb:2:in `block in <top (required)>'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/app/models/spree/product_decorator.rb:1:in `class_eval'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/app/models/spree/product_decorator.rb:1:in `<top (required)>'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/lib/spree_searchkick/engine.rb:16:in `block in activate'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/lib/spree_searchkick/engine.rb:15:in `glob'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/bundler/gems/spree_searchkick-790bcb97d8da/lib/spree_searchkick/engine.rb:15:in `activate'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `instance_exec'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:446:in `block in make_lambda'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `call'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:192:in `block in simple'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `block in call'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `each'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:504:in `call'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /home/palpandi/projects/Spree/mystore/config/environment.rb:5:in `<top (required)>'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application.rb:92:in `preload'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /home/palpandi/.rvm/gems/ruby-2.2.1/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/palpandi/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

**Comment by ronzalo** [comment]
Fixed with https://github.com/ronzalo/spree_searchkick/commit/310da7340021f86ae12eb09766ad96b0b5ed9224
