### ISSUE TITLE
Outdated typehead.bundle.js

### ISSUE THREAD

**Issue by zhengpd** [ronzalo/spree_searchkick#16]
The [last commit](https://github.com/twitter/typeahead.js/commit/588440f66559714280628a4f9799f0c4eb880a4a) of [original typehead.js](https://github.com/twitter/typeahead.js) provided by Twitter is in 2015, which is a bit outdated. Please consider to use [corejavascript/typeahead.js](https://github.com/corejavascript/typeahead.js). The latter is under active development, and fixed the async bug reported at https://github.com/twitter/typeahead.js/pull/1367.

**Comment by ronzalo** [comment]
Thanks, fixed in master @zhengpd
