### ISSUE TITLE
 GET http://autocomplete/products.json net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by raj23manj** [ronzalo/spree_searchkick#5]
Hi,

 I'm trying to use the gem and followed all the steps from your document. After restarting the server I was getting this error on my browser console. 

 GET http://autocomplete/products.json net::ERR_NAME_NOT_RESOLVED

On digging deep into the source code from here on master branch,

/app/assets/javascripts/spree/frontend/spree_searchkick.js

I found this being used "Spree.mountedAt()". The issue is we are not able to figure this out, and where is it mounted. 

When we  tried hitting this url manually we were able to fetch the data.

http://localhost:3000/autocomplete/products.json?keywords=ruby

Some how the domain name is not getting added. Any insights on this would be helpful.

Thanks In Advance.

**Comment by ronzalo** [comment]
Solved.

Thanks @raj23manj
